# Generated by Django 6.0.7 on 2026-08-02 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "package",
                    models.CharField(
                        choices=[
                            ("signpost", "2-Page Signpost — $25/year"),
                            ("starter", "Starter — $280"),
                            ("pro", "Pro — $480"),
                            ("custom", "Custom quote"),
                        ],
                        default="signpost",
                        max_length=20,
                    ),
                ),
                ("business_name", models.CharField(max_length=200)),
                ("contact_name", models.CharField(max_length=200)),
                (
                    "phone",
                    models.CharField(
                        help_text="WhatsApp number, e.g. 0776298873", max_length=20
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="What the business sells, existing socials, etc.",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=8),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending payment"),
                            ("awaiting_payment", "Awaiting payment"),
                            ("paid", "Paid"),
                            ("failed", "Payment failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("ecocash", "Ecocash"),
                            ("onemoney", "OneMoney"),
                            ("web", "Paynow web checkout"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("poll_url", models.URLField(blank=True)),
                ("paynow_status", models.CharField(blank=True, max_length=50)),
                (
                    "raw_response",
                    models.TextField(
                        blank=True, help_text="Last raw status response, for debugging."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_attempts",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
