# Generated by Django 6.0.7 on 2026-08-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="package",
            field=models.CharField(
                choices=[
                    ("signpost", "Signpost — $25/year"),
                    ("basic", "Basic — $120"),
                    ("standard", "Standard — $250"),
                    ("premium", "Premium — $370"),
                    ("custom", "Custom quote"),
                ],
                default="signpost",
                max_length=20,
            ),
        ),
    ]
