# Generated by Django 6.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_package"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="package",
            field=models.CharField(
                choices=[
                    ("signpost", "Signpost — $25/year"),
                    ("basic", "Basic — $80"),
                    ("standard", "Standard — $200"),
                    ("premium", "Premium — $370"),
                    ("custom", "Custom quote"),
                ],
                default="signpost",
                max_length=20,
            ),
        ),
    ]
