# Generated by Django 6.0.7 on 2026-08-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("client_name", models.CharField(blank=True, max_length=200)),
                (
                    "summary",
                    models.CharField(
                        help_text="One-line summary shown on cards.", max_length=300
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "package",
                    models.CharField(
                        choices=[
                            ("signpost", "Signpost"),
                            ("starter", "Starter"),
                            ("pro", "Pro"),
                            ("custom", "Custom build"),
                        ],
                        default="starter",
                        max_length=20,
                    ),
                ),
                ("live_url", models.URLField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="portfolio/covers/"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show on the homepage."
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
