# Generated by Django 6.0.7 on 2026-08-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="package",
            field=models.CharField(
                choices=[
                    ("signpost", "Signpost"),
                    ("basic", "Basic"),
                    ("standard", "Standard"),
                    ("premium", "Premium"),
                    ("custom", "Custom build"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
    ]
